# message 1465

std_msgs/Header header

BynavMessageHeader bynav_msg_header

string ins_status
string position_type


float64 latitude
float64 longitude
float64 altitude

float32 undulation

float64 north_velocity
float64 east_velocity
float64 up_velocity

float64 roll
float64 pitch
float64 azimuth

float32 latitude_std
float32 longitude_std
float32 altitude_std

float32 north_velocity_std
float32 east_velocity_std
float32 up_velocity_std

float32 roll_std
float32 pitch_std
float32 azimuth_std

BynavExtendedSolutionStatus extended_status

uint16 seconds_since_update
